<?xml version="1.0" standalone="no"?>
<!DOCTYPE QML SYSTEM "QML_V3.dtd">

<QML>

<QUESTION DESCRIPTION="@MOVIEID" TYPE="text/plain" >
<ANSWER QTYPE="FLASH" COMMENT="Y" SHUFFLE="N">
<CHOICE ID="@MOVIEID_1">
<CONTENT WIDTH="@MOVIEWIDTH" HEIGHT="@MOVIEHEIGHT" TYPE="NULL">@MOVIEID_2</CONTENT></CHOICE>
@RD_CHOICE_INTERACTIONS
</ANSWER>
<OUTCOME ID="Passed" CONTINUE="TRUE">
<CONDITION >"@MOVIEID_3" MATCHES NOCASE "C"</CONDITION>
<CONTENT TYPE="text/plain">You passed the simulation as a whole</CONTENT>
</OUTCOME>
<OUTCOME ID="Failed" CONTINUE="TRUE">
<CONDITION >"@MOVIEID_4" MATCHES NOCASE "W"</CONDITION>
<CONTENT TYPE="text/plain">You failed the simulation as a whole</CONTENT>
</OUTCOME>
@RD_OUTCOME_INTERACTIONS
</QUESTION>

</QML>
